name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: "Use cache"
                type: boolean
                default: false

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: my-react-app

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: 20.x
            
            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npx vitest
            
            - name: Run Build
              run: npm run build

            - name: Deploying to nonprod
              run: echo Deploying to nonprod 

