name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            node-version:
                description: "Node version"
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x


jobs:
    build:
        runs-on: ubuntu-latest
        needs: 
            - install-deps
        defaults:
            run:
                working-directory: my-react-app

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: ${{inputs.node-version}}
            
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: my-react-app/node_modules
                key: ${{ needs.install-deps.outputs.HASH }}

            - name: Run Tests
              run: npx vitest
            
            - name: Run Build
              run: npm run build

            - name: Deploying to nonprod
              run: echo Deploying to nonprod 
    install-deps:
        runs-on: ubuntu-latest
        outputs:
            HASH: ${{steps.cache-key.outputs.HASH}}
        defaults:
            run:
                working-directory: my-react-app

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Calculate Cache Key
              id: cache-key
              run: echo "HASH=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT

            - name: Download Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with: 
                path: my-react-app/node_modules
                key: ${{steps.cache-key.outputs.HASH}}

            - name: Install Dependencies
              if: ${{!(steps.cache.outputs.cache-hit == 'true')}}
              run: npm ci


    linting:
        runs-on: ubuntu-latest
        needs:
            - install-deps
        defaults:
            run: 
                working-directory: my-react-app
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x

            - name: Download Cache Dependencies
              uses: actions/cache@v3
              with: 
                path: my-react-app/node_modules
                key: ${{needs.install-deps.outputs.HASH}}

            - name: Testing
              run: npx vitest

            - name: Linting
              run: Linting ...


                

            





