name: 15 - Working With Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility: 
        name: ${{matrix.os}}-${{matrix.node}}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false 
            matrix:
                os: [ubuntu-latest, window-latest]
                node: [20.x, 21.x]
                include:
                    - os: ubuntu-latest
                      node: 21.x
                      tag: experimental
                    
                    - os: ubuntu-latest
                      node: 18.x

        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node}}

            - name: Fail if experimental
              if: ${{matrix.tag}} == 'experimental'
              run: exit 1

            - name: Perform some tests
              run: | 
                echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
                sleep 10

            - name: Uploading test results
              run: echo "Uploading test results"


              

            
                
            


    
